if: tag IS present
dist: xenial
language: python
python:
- '3.8'
install:
- pip install wheel
script: echo "No build-time tests to run."
deploy:
  provider: pypi
  user: adamrehn
  distributions: bdist_wheel
  on:
    tags: true
  password:
    secure: qdK9VJzBqNrMmTxvOpXY2oPRakf+isbWM4Ld9IilzYofUGQX74xkMTcAO1A3Ffi6op5d/qTmPkX/kHDSDHN5ufYDKFkj2bYXvq57jHGG0xolAw0OUFy+BNK09h4IEOBxTFzrQG+l5XSPdxH86maJAxxX8dEe1DY4I5x4hghus5CSkcu0neUiOt6SKs3HAogB4BZHp71oCZDDdS102sFwo9PqPbShxlt0v65Vu/bNHTog5UWfs7uw8ZVXPxXZ0yYa53cCpsGL+2Ye8qy9vJAh9ENRXDFsWwAaSoK6Vq0WRoKh5Pq8vbWGscE4fFcBFnmNHnnU2vLxdfPvdcX+O5Rh/rSvQXbEGLd5oLKgj1mNiCn6qMorI3D2OgRf/unqH+VSWW9m5zITqEml0jRwGOZ1GFGsBGnsyuAcnN6m8+i+BeW1D0usjBTeesfH049Y5uemsictJBefCWDX2WB2bWOD23S70BsmOMN+u3fq6clTyJvKupPDAFuAVn6iVby/t7kcbrxHsNgXTKAHHUKWYkLsX0pOY0SJFZ2232Sa9f7b+NeSVpYughulTRZwZ7HpYTdvLC4i77kDYPQ6evkkBFgmtG7dQ2Rb1G+7MOSNowsAGgzjrHk4tJfnCjVwoB695mgl2YE1p4+rP1ni1UPKmBJuE5Vw4Evr7RjoR5HvVRfPit0=
